<?php
    define("TIME_OUT",200);
    define("ATTEMPT_LIMIT",5);
    define("DB_SERVER_NAME","localhost");
    define("DB_USER","phpAgent");
    define("DB_PASSWORD","Test1234");
    define("DB_NAME","musicplatform_db");
    date_default_timezone_set("America/Vancouver");
?>